### ISSUE TITLE
增加正则表达式的支持

### ISSUE THREAD

**Issue by asforest** [jrotty/TEReplace#1]
今天博客更换链接插件，所有图片不出所料全挂掉了，还好有大佬的TEReplace，在1分钟内就全搞定了，真的好方便啊。
不过替换时的内容可以增加正则表达式的支持吗？有些内容替换规则较麻烦一些我仍然是手动替换的，要是支持正则表达式就简直完美了呢

另外yaofan.jpg可还行(刚开始还没注意到)

**Comment by jrotty** [comment]
不是很会这个，所以没办法

**Comment by asforest** [comment]
那没事没事
